### ISSUE TITLE
Error cctools

### ISSUE THREAD

**Issue by skrew** [javacom/toolchain4#1]
/home/xxx/toolchain4/src/cctools/otool/print_objc.c:34:31: error: objc/objc-runtime.h: No such file or directory
/home/xxx/toolchain4/src/cctools/otool/print_objc.c:147: error: expected identifier or â(â before âNXConstantStringâ
/home/xxx/toolchain4/src/cctools/otool/print_objc.c: In function âprint_objc_segmentâ:
/home/xxx/toolchain4/src/cctools/otool/print_objc.c:635: warning: implicit declaration of function âCLS_GETINFOâ
/home/xxx/toolchain4/src/cctools/otool/print_objc.c:635: error: âCLS_METAâ undeclared (first use in this function)
/home/xxx/toolchain4/src/cctools/otool/print_objc.c:635: error: (Each undeclared identifier is reported only once
/home/xxx/toolchain4/src/cctools/otool/print_objc.c:635: error: for each function it appears in.)
/home/xxx/toolchain4/src/cctools/otool/print_objc.c:674: error: âCLS_CLASSâ undeclared (first use in this function)

**Comment by javacom** [comment]
edit toolchain/src/cctools/otools/print-objc.c,comment all because there is no objc runtime headers on ubuntu

&#35;if 0
.....(source code of print-objc.c) 

&#35;endif

**Comment by MyPod-zz** [comment]
I have a workaround, but it requires you not to use toolchain.sh to build odcctools: I reuse the odcctools in cctools2odcctools and do the following:

cd otool
gcc -x objective-c -Wall -Wno-import  -DHAVE_CONFIG_H    -I. -I. -I../include -I../include   -g -O2 -fno-builtin-round -fno-builtin-trunc -no-cpp-precomp -mdynamic-no-pic  -c -o print_objc.o print_objc.c -DCLS_META=0x2L -DCLS_CLASS=0x1L -D"CLS_GETINFO(cls,infomask)"="((cls)->info & infomask)"
cd .. && make

I'm not much into make syntax, but all that's missing is just a few defines, so it's not worth to cut out the entire file.
