### ISSUE TITLE
error: C compiler doesn't work.

### ISSUE THREAD

**Issue by MyPod-zz** [javacom/toolchain4#3]
Hello and thanks for making an almost automated toolchain.
I have downloaded the iPhoneSDK4.2 4.3 5.0 and the command./toolchain.sh buildsys<version> ended well for each one. Xar also did fine.
Unfortunately I'm stuck with this error when it comes to ./toolchain.sh cctools:

Configuring cctools-iphone...
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... arm-apple-darwin9
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/toolchain4/bld/cctools-iphone':
configure: error: C compiler cannot create executables
See`config.log' for more details
make: **\*  No rule to make the target "clean".  Stopped.
Building cctools-iphone...
Build progress logged to: /toolchain4/bld/cctools-iphone/make.log
Build & install failed. Check make.log and install.log

I'm using Ubuntu 10.10 64bit as VM with VirtualBox. I did the trick with setting gcc as 4.4 but things didn't change that much. You may also need to add a backslash \ as here:
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.4 44  \
 --slave /usr/bin/g++ g++ /usr/bin/g++-4.4 \
 --slave /usr/bin/gcov gcov /usr/bin/gcov-4.4

**Comment by H2CO3** [comment]
I bet the -isysroot command line parameter for arm-apple-darwin9-gcc is missing...

**Comment by MyPod-zz** [comment]
So i should edit toolchain.sh and add it as a building flag specifying the effective sysroot I'm gonna use?

**Comment by H2CO3** [comment]
Yes, exactly.

Envoyé de mon iPhone

**Comment by MyPod-zz** [comment]
Actually, README and toolchain.sh give different instructions.
I'm starting by a clean git again. I noticed I have the MacOSX10.5.pkg which I don't know where to put.

Anyway mine was a problem with architectures, as I use a 64bit Ubuntu and ./toolchain.sh imposes CFLAGS="-m32"  LDFLAGS="-m32" on the cctools configure. I suggest to check architecture with switch/case '/usr/bin/arch' and decide consequently if use those flags or not.

The error about objc/objc_runtime.h not found in /toolchain4/src/cctools/otool/print_objc.c: now I'm stuck with this. Doing find /toolchain4 -name *runtime.h I have:
./sys/usr/include/objc/runtime.h
./sys50/usr/include/objc/runtime.h
and 2 other results in sdks (but they are a copy of those above, aren't they?)
It's really needed to comment out the whole file?

Now I'm stuck with toolchain.sh llvmgcc.
make stop at a certain point (libgcc_eh.a) for a not-better-described fatal error.

One last question I have if it's needed to set the target to something as old as darwin9. I mean I acknowledge not all jail breakers have passed to 5.x but I think I can step up to 10.

**Comment by javacom** [comment]
use 32bit OS

**Comment by H2CO3** [comment]
Thanks!
